### MEMBER 생성
GET localhost:8080/create-member
Accept: application/json

### MEMBER 생성 with Flush
GET localhost:8080/create-member-with-flush
Accept: application/json

### MEMBER 생성 with Flush, Clear
GET localhost:8080/create-member-with-flush-and-clear
Accept: application/json

### 같은 트랜잭션 안에서 엔티티의 동일성
GET localhost:8080/test-equality
Accept: application/json

### 새로운 객체로 매핑할 경우 동일성
GET localhost:8080/test-equality-with-mapping
Accept: application/json

### 채팅(Chat, ChatRoom, ChatParticipant) 생성
GET localhost:8080/create-chat
Accept: application/json

### 채팅(Chat, ChatRoom, ChatParticipant)
GET localhost:8080/chat-room/1
Accept: application/json

### 채팅(Chat, ChatRoom, ChatParticipant) Using Reference
GET localhost:8080/chat-room-using-reference/1
Accept: application/json

### 즉시로딩에서의 N+1
GET localhost:8080/problem-when-eager
Accept: application/json

### 지연로딩에서의 N+1
GET localhost:8080/problem-when-lazy
Accept: application/json

### 지연로딩에서의 N+1 해결 by fetch join
GET localhost:8080/solve-problem-when-lazy
Accept: application/json

### 페이징, 정렬 기능
GET localhost:8080/paging-and-sorting
Accept: application/json
